// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// level_monitor //
// ------------- //

#define level_monitor_wrap_target 0
#define level_monitor_wrap 7

static const uint16_t level_monitor_program_instructions[] = {
            //     .wrap_target
    0xa0c3, //  0: mov    isr, null       side 0     
    0x4016, //  1: in     pins, 22        side 0     
    0xa026, //  2: mov    x, isr          side 0     
    0x00a5, //  3: jmp    x != y, 5       side 0     
    0x0000, //  4: jmp    0               side 0     
    0xa041, //  5: mov    y, x            side 0     
    0x8000, //  6: push   noblock         side 0     
    0xd024, //  7: irq    wait 4          side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program level_monitor_program = {
    .instructions = level_monitor_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config level_monitor_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + level_monitor_wrap_target, offset + level_monitor_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ---------- //
// time_stamp //
// ---------- //

#define time_stamp_wrap_target 0
#define time_stamp_wrap 7

static const uint16_t time_stamp_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, !null                   
    0x0043, //  1: jmp    x--, 3                     
    0x0000, //  2: jmp    0                          
    0x00c5, //  3: jmp    pin, 5                     
    0x0001, //  4: jmp    1                          
    0xa0c9, //  5: mov    isr, !x                    
    0x8000, //  6: push   noblock                    
    0xc044, //  7: irq    clear 4                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program time_stamp_program = {
    .instructions = time_stamp_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config time_stamp_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + time_stamp_wrap_target, offset + time_stamp_wrap);
    return c;
}
#endif
